# Generated by Django 3.0.7 on 2020-06-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_regular_user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sector',
            field=models.CharField(blank=True, choices=[('Finance', 'Finance'), ('Technology', 'Technology'), ('Marketing', 'Marketing'), ('Consulting', 'Consulting'), ('Engineering', 'Engineering')], max_length=40),
        ),
    ]
