# Generated by Django 3.0.7 on 2020-06-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20200626_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.Post'),
        ),
    ]
